spring:
  thymeleaf.content-type: text/html
  thymeleaf.cache: false
  thymeleaf.mode: LEGACYHTML5
  http:
      multipart:
        maxFileSize: 50Mb
        maxRequestSize: 100Mb
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #响应时间统一格式化
    time-zone: GMT+8
# mybatis配置
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.aisino.entity
  configuration:
    call-setters-on-nulls: true

# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#允许优雅中止项目
endpoints:
  shutdown:
    enabled: true
    path: /duyiping
    sensitive: false
file:
  defaultPath: /springboot/zlspdf/



