server:
  # 端口号
  port: 9017
  context-path: /aisino/
spring:
    application:
      name: service-zls
    datasource:
      dynamic:
        primary: master #设置默认的数据源或者数据源组,默认值即为master
        datasource:
          master: #自建oracle数据库
            url: jdbc:oracle:thin:@192.168.88.160:1521/CDFGSDB
            username: tfhtds
            password: tfhtds123
            driver-class-name: oracle.jdbc.driver.OracleDriver
          slave: #权限框架mysql库
            url: jdbc:mysql://fptypt.schtxxcdfgs.com:8004/wechat?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
            username: root
            password: Root!!2018
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
#    datasource:
#        name: test
#        # 数据库连接
#        url: jdbc:mysql://fptypt.schtxxcdfgs.com:8004/kpfwvue?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#        username: root
#        password: Root!!2018
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 最大活跃连接数
        maxActive: 20
        # 指定启动连接池时，初始建立的连接数量
        initialSize: 1
        # 最大等待时间
        maxWait: 60000
        # 指定必须保持连接的最小值
        minIdle: 1
        # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
        timeBetweenEvictionRunsMillis: 60000
        # 指定一个空闲连接最少空闲多久后可被清除
        minEvictableIdleTimeMillis: 300000
        # 指定获取连接时连接校验的sql查询语句
        validationQuery: select 'x'
        # 当连接空闲时，是否执行连接测试
        testWhileIdle: true
        # 当从连接池借用连接时，是否测试该连接
        testOnBorrow: false
        # 设置当连接被归还时，是否要提交所有还未完成的事务
        testOnReturn: false
        # 指定是否池化statements
        poolPreparedStatements: true
        # 指定最大的打开的prepared statements数量
        maxOpenPreparedStatements: 20
    devtools:
      restart:
#        不自动重启
        enabled: true
      livereload:
        enabled: true
logging:
  level:
    com.aisino.mapper: debug
#nuonuo.config.kpaddr: http://nnfpbox.nuonuocs.cn/shop/buyer/allow/cxfKp/cxfServerKpOrderSync.action
#nuonuo.config.queryaddr: http://nnfpbox.nuonuocs.cn/shop/buyer/allow/ecOd/queryElectricKp.action
#nuonuo.config.zfQueryAddr: http://nnfpbox.nuonuocs.cn/shop/buyer/allow/cxfKp/invalidInvoice.action
#nuonuo.config.kpcsQueryAddr: http://nnfpbox.nuonuocs.cn/shop/buyer/allow/cxfKp/cxfKp/reInvoice.do

# 蓉票儿同步接口
#rongpiaoer.tongbu: https://api-rpr.yewifi.com/life-service/callback?appkey=91510100395911836B
#rongpiaoer.rongPiaoErGongYao: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEya44tKWYg3nGpWIr3fVTCJM//RX3uR5pzY3tUGeviW5pOl42sLbJ/MyaBqNqbEXqEUwn0Kx3ipYnVD7qcplpA0hXxKX7lReBu1l5jNDHnOcBWmSSbYb/5UeLskdiX11ofTtz3oRzJwPCBAyR7MXVXTsMIVE81Aree1/ugcJNPQIDAQAB
#简阳发票pdf本地保存路径
jianyang.filepath: /springboot/zlspdf/
jianyang.port: localhost:80
#基路径
rootFilePath: /wechatpay-upload/
